#!/bin/bash


# install dependencies
libgtk-3-0 
libasound2 
libgconf-2-4

# download and extract playwright


libgstreamer-plugins-base1.0-0
libopus0 
libwoff2dec1 
libharfbuzz-icu0 
libgstallocators-1.0.0
libgstapp-1.0.0 
libgstbase-1.0.0
libgstpbutils-1.0.0 
libgstaudio-1.0.0 
libgsttag-1.0.0 
libgstvideo-1.0.0 
libgstgl-1.0.0 
libgstfft-1.0.0 
libenchant2 
libsecret-1-0 
libhyphen0 
libevdev2 
libgudev-1.0-0 
libgles2-mesa-dev 
libx264-dev
