name: myenv
dependencies:
  - alembic=1.9.2
  - aniso8601=9.0.1
  - beautifulsoup4=4.11.1
  - bs4=0.0.1
  - certifi=2022.12.7
  - charset-normalizer=3.0.1
  - click=8.1.3
  - colorama=0.4.6
  - Flask=2.2.2
  - Flask-Login=0.6.2
  - Flask-Migrate=4.0.3
  - Flask-RESTful=0.3.9
  - Flask-SQLAlchemy=3.0.3
  - greenlet=2.0.1
  - gunicorn=20.1.0
  - idna=3.4
  - itsdangerous=2.1.2
  - Jinja2=3.1.2
  - Mako=1.2.4
  - MarkupSafe=2.1.2
  - playwright=1.30.0
  - pyee=9.0.4
  - pytz=2022.7.1
  - requests=2.28.2
  - six=1.16.0
  - soupsieve=2.3.2.post1
  - SQLAlchemy=2.0.0
  - TikTokApi=5.2.2
  - typing_extensions=4.4.0
  - urllib3=1.26.14
  - Werkzeug=2.2.2
  - mysqlclient
