"""created UrlUrl model

Revision ID: 6875dacb2af6
Revises: 30b4c1a82704
Create Date: 2023-01-30 18:22:16.243769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6875dacb2af6'
down_revision = '30b4c1a82704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_list')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('url_list')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_list', sa.VARCHAR(), nullable=False))

    op.create_table('url_list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
